version: '3.8'

services:
  naik-api:
    build: .
    ports:
      - 8001:8000
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --loop asyncio
  nginx:
      image: nginx:latest
      ports:
        - "8080:8080"