--- fees generated by top 10 pairs---

SELECT 
    swaps.token0_symbol,
    swaps.token1_symbol,
    pools.fee_percent,
    SUM((ABS(swaps.amount0_usd) + ABS(swaps.amount1_usd))/2) * pools.fee_percent AS fee_collected
FROM
    ethereum.uniswapv3.ez_swaps swaps
LEFT JOIN ethereum.uniswapv3.ez_pools pools ON swaps.pool_address = pools.pool_address
GROUP BY 1, 2, 3
HAVING fee_collected IS NOT NULL
ORDER BY 4 DESC
LIMIT 10



-- ---------total fees by fee tier--------
-- SELECT 
--     pools.fee_percent,
--     SUM((ABS(swaps.amount0_usd) + ABS(swaps.amount1_usd))/2) * pools.fee_percent AS fee_collected
-- FROM
--     ethereum.uniswapv3.ez_swaps swaps
-- LEFT JOIN ethereum.uniswapv3.ez_pools pools ON swaps.pool_address = pools.pool_address
-- GROUP BY 1 
